Fiap.Exemplo02.MVC.Web/Controllers/AlunoController.cs
using Fiap.Exemplo02.Dominio.Models;
using Fiap.Exemplo02.MVC.Persistencia.UnitsOfWork;
using Fiap.Exemplo02.MVC.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo02.MVC.Web.Controllers
{
    public class AlunoController : Controller
    {
        // private PortalContext _context = new PortalContext();
        private UnitOfWork _unit = new UnitOfWork();

        #region GET
        [HttpGet]
        public ActionResult Cadastro(string msg)
        {
            var viewModel = new AlunoViewModel()
            {
                ListaGrupo = ListarGrupos(),
                Mensagem = msg,
                DataNascimento = DateTime.Now

            };
            
            return View(viewModel);
        }

        private SelectList ListarGrupos()
        {
            var lista = _unit.GrupoRepository.Listar();
            return new SelectList(lista, "Id", "Nome");
        }

        [HttpGet]
        public ActionResult Listar()
        {
            //Include -> Busca o relacionamento (preenche o grupo que o aluno possui), faz o join
            var viewModel = new AlunoViewModel()
            {
                Alunos = _unit.AlunoRepository.Listar(),
                ListaGrupo = ListarGrupos()
                
            };
            CarregarComboGrupo();
            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            //Buscar o objeto (aluno no banco
            var aluno = _unit.AlunoRepository.BuscarPorId(id);
            var viewModel = new AlunoViewModel()
            {
                ListaGrupo = ListarGrupos(),
                Nome = aluno.Nome,
                Bolsa = aluno.Bolsa,
                Desconto = aluno.Desconto,
                Id = aluno.Id,
                DataNascimento = aluno.DataNascimento,
                GrupoId = aluno.GrupoId
             };
             // manda o aluno para a view
            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Buscar(string nomeBusca, int? IdBusca)
        {
            ICollection<Aluno> lista;
           
                lista = _unit.AlunoRepository.BuscarPor(a => 
                a.Nome.Contains(nomeBusca) && (a.GrupoId == IdBusca ||   IdBusca == null));
            
            CarregarComboGrupo();
            var viewModel = new AlunoViewModel()
            {
                ListaGrupo = ListarGrupos(),
                Alunos = lista
            };
            //retorna para a view Listar com a lista
            return PartialView("_tabela", lista);
        }
        [HttpGet]
        public ActionResult ValidarNome(string nome)
        {
            var aluno = _unit.AlunoRepository.BuscarPor(a => a.Nome == nome);
            //Retorna um JSON { "existe" : true/false }
            return Json (new { existe = aluno.Any() }, JsonRequestBehavior.AllowGet);
        }

        #endregion


        #region POST
        [HttpPost]
        public ActionResult Cadastro(AlunoViewModel alunoViewModel)
        {
            //automap
            if (ModelState.IsValid)
            {
                var aluno = new Aluno()
                {
                    Nome = alunoViewModel.Nome,
                    DataNascimento = alunoViewModel.DataNascimento,
                    Bolsa = alunoViewModel.Bolsa,
                    Desconto = alunoViewModel.Desconto,
                    GrupoId = alunoViewModel.GrupoId,
                    Id = alunoViewModel.Id,


                };
                _unit.AlunoRepository.Cadastrar(aluno);
                _unit.Salvar();
                return RedirectToAction("Cadastro", new { msg = "Aluno Cadastrado" });
            }
            else
            {
                alunoViewModel.ListaGrupo = ListarGrupos();
                return View(alunoViewModel);
            }
        }

        [HttpPost]
        public ActionResult Editar(Aluno aluno)
        {
            _unit.AlunoRepository.Atualizar(aluno);
            _unit.Salvar();
            return RedirectToAction("Listar", new { msg = "Aluno Editado"});
        }
        [HttpPost]
        public ActionResult Excluir(int AlunoId)
        {
            _unit.AlunoRepository.Remover(AlunoId);
            TempData["msg"] = "Aluno excluido";
            _unit.Salvar();
            return RedirectToAction("Listar");
        }

        #endregion

        #region DISPOSE
        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
        #endregion

        #region FUNCTION
        private void CarregarComboGrupo()
        {
            //envia para a tela os grupos para o select
            ViewBag.grupos = new SelectList(_unit.GrupoRepository.Listar(), "Id", "Nome");
        }
        #endregion







    }
}

Fiap.Exemplo02.MVC.Web/Controllers/GrupoController.cs
using Fiap.Exemplo02.Dominio.Models;
using Fiap.Exemplo02.MVC.Persistencia.UnitsOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo02.MVC.Web.Controllers
{
    public class GrupoController : Controller
    {
        UnitOfWork _unit = new UnitOfWork();
        // GET: Grupo
        public ActionResult Cadastro()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Cadastro(Grupo grupo)
        {
            _unit.GrupoRepository.Cadastrar(grupo);
            _unit.Salvar();
            TempData["msg"] = "Grupo Cadastrado";
            return RedirectToAction("Cadastro");
        }

        public ActionResult Listar()
        {
            var lista = _unit.GrupoRepository.Listar();
            return View(lista);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            var grupo = _unit.GrupoRepository.BuscarPorId(id);
            return View(grupo);
        }
        [HttpPost]
        public ActionResult Editar(Grupo grupo)
        {
            _unit.GrupoRepository.Atualizar(grupo);
            _unit.ProjetoRepository.Atualizar(grupo.Projeto);
            _unit.Salvar();
            TempData["msg"] = "Grupo atualizado";
            return RedirectToAction("Listar");
        }


    }
}

Fiap.Exemplo02.MVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fábrica", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Aluno <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastro de Aluno", "Cadastro", "Aluno")</li>
                            <li>@Html.ActionLink("Alunos", "Listar", "Aluno")</li>
                        </ul>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Grupo <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastro de Grupo", "Cadastro", "Grupo")</li>
                            <li>@Html.ActionLink("Grupos", "Listar", "Grupo")</li>
                        </ul>
                    </li>
               </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/scripts/jquery.validate.js"></script>
    <script src="~/scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>
    <!-- area para as paginas adicionar conteudo-->
    @RenderSection("scripts",false)
</body>
</html>